- name: Automate the Docker deployment of the Yolo app using Ansible
  hosts: all
  become: true

  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: Wait for SSH
      wait_for:
        port: 22
        timeout: 300

  roles:
    - role: common
      tags: ['common','setup']
    - role: mongo
      tags: ['mongo','database']
    - role: backend
      tags: ['backend','api']
    - role: frontend
      tags: ['frontend','web']
  
  post_tasks:
    - name: Show running containers
      command: docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
      register: docker_ps
      changed_when: false

    - debug:
        var: docker_ps.stdout_lines

